default:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 16
      account: rd05334
      user: dbtmjh
      database: analytics
      warehouse: transforming
      schema: dbt_mjh
      password: h@llberg10L3if
      role: transformer
